# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0006_auto_20161027_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[(b'PUBLIC', b'Public'), (b'SERVERONLY', b'Public to local'), (b'FOAF', b'Friends of friends'), (b'SERVERONLY', b'Local friends'), (b'FRIENDS', b'friend selected'), (b'PRIVATE', b'Myself only')], default=b'text/plain', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[(b'PUBLIC', b'Public'), (b'SERVERONLY', b'Public to local'), (b'FOAF', b'Friends of friends'), (b'SERVERONLY', b'Local friends'), (b'FRIENDS', b'friend selected'), (b'PRIVATE', b'Myself only')], default=b'PUBLIC', max_length=20),
        ),
    ]
