# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagForPost',
        ),
    ]
