# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0002_delete_tagforpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_author_friends_+', to='socialDistribution.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='git',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
