# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 22:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import web_api.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_username', models.CharField(blank=True, max_length=35, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('host', models.URLField()),
                ('friend_request_received', models.ManyToManyField(blank=True, related_name='_author_friend_request_received_+', to='web_api.Author')),
                ('friend_request_sent', models.ManyToManyField(blank=True, related_name='_author_friend_request_sent_+', to='web_api.Author')),
                ('friends', models.ManyToManyField(blank=True, related_name='_author_friends_+', to='web_api.Author')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(default=b'')),
                ('publish_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_api.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=150)),
                ('origin', models.CharField(default=b'http://127.0.0.1:8000/posts', max_length=150)),
                ('description', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('category', web_api.utils.ListField(blank=True, default=[])),
                ('visibility', models.CharField(choices=[(b'PUBLIC', b'Public'), (b'SERVERONLY', b'Public to local'), (b'FOAF', b'Friends of friends'), (b'SERVERONLY', b'Local friends'), (b'FRIENDS', b'friend selected'), (b'PRIVATE', b'Myself only')], default=b'PUBLIC', max_length=20)),
                ('publish_time', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[(b'text/plain', b'text/plain'), (b'text/markdown', b'text/markdown')], default=b'text/markdown', max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_api.Author')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_api.Post'),
        ),
    ]
