# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(default=b'http://127.0.0.1:8000'),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default=b'http://127.0.0.1:8000'),
        ),
    ]
