# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('source', models.URLField(blank=True)),
                ('origin', models.URLField(blank=True)),
                ('description', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, default=b'', max_length=50, null=True)),
                ('visibility', models.CharField(choices=[(b'PUBLIC', b'Public'), (b'SERVERONLY', b'Local only'), (b'FOAF', b'Friends of friends'), (b'FRIENDS', b'Friends'), (b'PRIVATE', b'Myself only')], default=b'PUBLIC', max_length=20)),
                ('published', models.DateTimeField()),
                ('contentType', models.CharField(choices=[(b'text/plain', b'text/plain'), (b'text/markdown', b'text/markdown'), (b'text/x-markdown', b'text/x-markdown')], default=b'text/markdown', max_length=15)),
            ],
        ),
    ]
