# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0002_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='friend_request_received',
        ),
        migrations.RemoveField(
            model_name='author',
            name='friend_request_sent',
        ),
    ]
