# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0002_auto_20161128_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotecomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='remotecomment',
            name='post',
        ),
        migrations.DeleteModel(
            name='RemoteComment',
        ),
    ]
