# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid
import web_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0002_auto_20161118_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.URLField(editable=False)),
                ('photo', models.ImageField(upload_to=web_api.models.folder_name)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_api.Author')),
            ],
        ),
    ]
