# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0002_node_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(blank=True),
        ),
    ]
