# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0002_foreignpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_api.Author'),
        ),
    ]
