# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0003_auto_20161102_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='accepted',
        ),
    ]
