# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0003_auto_20161128_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='contentType',
            field=models.CharField(default=b'text/markdown', editable=False, max_length=35),
        ),
    ]
