# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0003_auto_20161023_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.CharField(default='ualbert.ca', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(default='source.ca', max_length=150),
            preserve_default=False,
        ),
    ]
