# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0004_remove_friendrequest_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[(b'PUBLIC', b'Public'), (b'SERVERONLY', b'Local only'), (b'FOAF', b'Friends of friends'), (b'FRIENDS', b'Friends'), (b'PRIVATE', b'Myself only')], default=b'PUBLIC', max_length=20),
        ),
    ]
