# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0004_auto_20161123_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(default=b'')),
                ('published', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_api.Author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_api.ForeignPost')),
            ],
        ),
    ]
