# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0004_comment_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignpost',
            name='description',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
