# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0005_auto_20161102_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default=b'http://127.0.0.1:8000/posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(),
        ),
    ]
