# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0005_auto_20161129_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='foreign_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_api.ForeignPost'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_api.Post'),
        ),
    ]
