# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0005_remotecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_api.Author'),
        ),
    ]
