# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0007_auto_20161130_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
