# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0007_auto_20161101_2040'),
        ('web_api', '0007_auto_20161101_2042'),
    ]

    operations = [
    ]
