# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0008_auto_20161130_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id',
            new_name='guid',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='published',
            new_name='pubDate',
        ),
    ]
