# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0008_merge_20161101_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[(b'text/plain', b'text/plain'), (b'text/markdown', b'text/markdown')], default=b'text/markdown', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.CharField(default=b'http://127.0.0.1:8000/posts', max_length=150),
        ),
    ]
