# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0009_auto_20161130_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='guid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='pubDate',
            new_name='published',
        ),
    ]
