# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0009_auto_20161103_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(editable=False),
        ),
    ]
