# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0010_auto_20161104_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, default=b'', max_length=50, null=True),
        ),
    ]
